### ISSUE TITLE
Some questions about NPU

### ISSUE THREAD

**Issue by June1124** [NXP/imx_openwrt#1]
Hi, I want to build onnxruntime application based on QT on iMX8M Plus, I have set vsi_npu, but the model inference is still on the CPU, is there any relevant example of calling NPU inference based on C++ onnxruntime? And how to check the real-time performance of NPU?

**Comment by andynxp** [comment]
This repo is for openwrt. So not all the features are supported. Please try LSDK release package on:
https://www.nxp.com/design/software/embedded-software/i-mx-software/embedded-linux-for-i-mx-applications-processors:IMXLINUX
