### ISSUE TITLE
Update to latest OpenWRT

### ISSUE THREAD

**Issue by relaxibus** [NXP/imx_openwrt#4]
Would you update this repo to the latest OpenWRT?

**Comment by andynxp** [comment]
Thanks for your suggestion. We are working on it.
Currently v22.03.0 is new enough for development.

**Comment by relaxibus** [comment]
Hi Andy, great! I'm working on a new router for drones and unmanned systems applications based on the PicoCore iMX8MP fro FS-NET. Would love to use it with OpenWRT. Do you have a email where I could contact you and share ideas and works?
