### ISSUE TITLE
How to contact AndyNXP

### ISSUE THREAD

**Issue by relaxibus** [NXP/imx_openwrt#5]
Hi Andy, great! I'm working on a new router for drones and unmanned systems applications based on the PicoCore iMX8MP fro FS-NET. Would love to use it with OpenWRT. Do you have a email where I could contact you and share ideas and works?

**Comment by andynxp** [comment]
There is a forum on NXP website where is perfect place to share ideas and works, and of cause ask questions at:
https://community.nxp.com/t5/iMX-and-Vybrid-Support/bd-p/1007forum-board
Need to register first.
